CUDA_VISIBLE_DEVICES=1,2,3 python train.py --batchSize=3 \
                --crop_height=384 \
                --crop_width=768 \
                --max_disp=192 \
                --threads=8 \
                --data_path='./dataset/apolloscape/' \
                --training_list='lists/apolloscape_train.list' \
                --val_list='lists/apolloscape_val.list' \
                --save_path='./checkpoint/apolloscape_check/' \
                --resume='./pretrained/sceneflow_epoch_10.pth' \
                --lr=0.001 \
                --model='GANet_deep' \
                --nEpochs=100 2>&1 |tee logs/log_finetune_apolloscape.txt
